services:
  db:
    image: mysql:8.0
    container_name: flask_db
    restart: always
    env_file:
      - ${DOTENV_PATH}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: